CREATE DATABASE GCO;
GO

USE GCO;
GO
IF OBJECT_ID('dbo.Members', 'U') IS NULL
CREATE TABLE dbo.Members (
  Id NVARCHAR(32) NOT NULL PRIMARY KEY,
  Email NVARCHAR(320) NOT NULL UNIQUE,
  FullName NVARCHAR(160) NOT NULL,
  Instrument NVARCHAR(120) NOT NULL,
  Signature NVARCHAR(MAX) NOT NULL,
  Phone NVARCHAR(40) NULL,
  NationalId NVARCHAR(80) NULL,
  DateOfBirth DATE NULL,
  Nationality NVARCHAR(80) NULL,
  Address NVARCHAR(300) NULL,
  EmergencyName NVARCHAR(160) NULL,
  EmergencyPhone NVARCHAR(40) NULL,
  PhotoData NVARCHAR(MAX) NULL,
  PasswordHash NVARCHAR(300) NOT NULL,
  Consent BIT NOT NULL,
  Status NVARCHAR(32) NOT NULL DEFAULT 'pending',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  ApprovedAt DATETIME2 NULL
);
GO
USE GCO;
GO
CREATE LOGIN gco_app WITH PASSWORD = 'replace-with-a-strong-password';
CREATE USER gco_app FOR LOGIN gco_app;
ALTER ROLE db_datareader ADD MEMBER gco_app;
ALTER ROLE db_datawriter ADD MEMBER gco_app;
GO

USE GCO;
GO
IF OBJECT_ID('dbo.Admins', 'U') IS NULL
CREATE TABLE dbo.Admins (
  Username NVARCHAR(80) NOT NULL PRIMARY KEY,
  Email NVARCHAR(320) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(300) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
